add_test([=[AddTest.Basic]=]  /workspaces/tddExample/build-coverage/tests/example_test [==[--gtest_filter=AddTest.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AddTest.Basic]=]  PROPERTIES WORKING_DIRECTORY /workspaces/tddExample/build-coverage/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FactorialTest.HandlesZeroAndOne]=]  /workspaces/tddExample/build-coverage/tests/example_test [==[--gtest_filter=FactorialTest.HandlesZeroAndOne]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FactorialTest.HandlesZeroAndOne]=]  PROPERTIES WORKING_DIRECTORY /workspaces/tddExample/build-coverage/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FactorialTest.HandlesPositive]=]  /workspaces/tddExample/build-coverage/tests/example_test [==[--gtest_filter=FactorialTest.HandlesPositive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FactorialTest.HandlesPositive]=]  PROPERTIES WORKING_DIRECTORY /workspaces/tddExample/build-coverage/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CFuncsTest.GcdPositive]=]  /workspaces/tddExample/build-coverage/tests/example_test [==[--gtest_filter=CFuncsTest.GcdPositive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CFuncsTest.GcdPositive]=]  PROPERTIES WORKING_DIRECTORY /workspaces/tddExample/build-coverage/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CFuncsTest.GcdWithZeroAndNegative]=]  /workspaces/tddExample/build-coverage/tests/example_test [==[--gtest_filter=CFuncsTest.GcdWithZeroAndNegative]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CFuncsTest.GcdWithZeroAndNegative]=]  PROPERTIES WORKING_DIRECTORY /workspaces/tddExample/build-coverage/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FizzBuzz.testFizzBuzz]=]  /workspaces/tddExample/build-coverage/tests/example_test [==[--gtest_filter=FizzBuzz.testFizzBuzz]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FizzBuzz.testFizzBuzz]=]  PROPERTIES WORKING_DIRECTORY /workspaces/tddExample/build-coverage/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FizzBuzz.testBuzz]=]  /workspaces/tddExample/build-coverage/tests/example_test [==[--gtest_filter=FizzBuzz.testBuzz]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FizzBuzz.testBuzz]=]  PROPERTIES WORKING_DIRECTORY /workspaces/tddExample/build-coverage/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FizzBuzz.testFizzBuzzAndBuzz]=]  /workspaces/tddExample/build-coverage/tests/example_test [==[--gtest_filter=FizzBuzz.testFizzBuzzAndBuzz]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FizzBuzz.testFizzBuzzAndBuzz]=]  PROPERTIES WORKING_DIRECTORY /workspaces/tddExample/build-coverage/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  example_test_TESTS AddTest.Basic FactorialTest.HandlesZeroAndOne FactorialTest.HandlesPositive CFuncsTest.GcdPositive CFuncsTest.GcdWithZeroAndNegative FizzBuzz.testFizzBuzz FizzBuzz.testBuzz FizzBuzz.testFizzBuzzAndBuzz)
